/**
 * Event repository — mock implementation (no DB required).
 * Replace with DB-backed implementation when DATABASE_URL is available.
 */
import type { PortalEvent, EventFilters, PaginatedResult } from '@/types/domain';

const MOCK_EVENTS: PortalEvent[] = [
  {
    id: 1,
    slug: '3x3-exe-super-premier-sendai-2026-r1',
    name: '3x3.EXE SUPER PREMIER 2025-26 ROUND.1（Sendai）',
    description: '3x3.EXE SUPER PREMIERのラウンド1（仙台開催）。',
    location: 'ゼビオアリーナ仙台（宮城県仙台市太白区あすと長町1-4-10）',
    country: '日本',
    startDate: '2026-02-28',
    endDate: '2026-03-01',
    status: '終了',
    imageUrl: null,
    websiteUrl: 'https://3x3exe.com/superpremier/schedules/',
    xAccount: '3x3league',
    instagramAccount: '3x3.exe',
    tiktokAccount: null,
    participants: [
      { teamId: 1, status: 'confirmed' },
      { teamId: 3, status: 'confirmed' },
      { teamId: 4, status: 'confirmed' },
      { teamId: 5, status: 'confirmed' },
      { teamId: 6, status: 'confirmed' },
      { teamId: 7, status: 'confirmed' },
      { teamId: 8, status: 'confirmed' },
      { teamId: 9, status: 'confirmed' },
      { teamId: 10, status: 'confirmed' },
      { teamId: 11, status: 'confirmed' },
      { teamId: 12, status: 'confirmed' },
      { teamId: 13, status: 'confirmed' },
    ],
    updatedAt: '2026-03-06T00:00:00Z',
  },
  {
    id: 2,
    slug: '3x3-exe-super-premier-thailand-2026-r2-mega-bangna',
    name: '3x3.EXE SUPER PREMIER 2025-26 ROUND.2（Thailand / Mega Bangna）',
    description: '3x3.EXE SUPER PREMIERのラウンド2（タイ開催）。SHINAGAWA CITY.EXEが優勝、LUGANOが準優勝。得点王はDusan Samardzic（SHINAGAWA CITY.EXE、36得点）。',
    location: 'Mega Bangna - Food Walk Plaza（Samut Prakan, Thailand）',
    country: 'タイ',
    startDate: '2026-03-21',
    endDate: '2026-03-22',
    status: '終了',
    imageUrl: null,
    websiteUrl: 'https://3x3exe.com/superpremier/schedules/',
    xAccount: '3x3league',
    instagramAccount: '3x3.exe',
    tiktokAccount: null,
    participants: [
      { teamId: 1, status: 'confirmed' },
      { teamId: 3, status: 'confirmed' },
      { teamId: 4, status: 'confirmed' },
      { teamId: 5, status: 'confirmed' },
      { teamId: 6, status: 'confirmed' },
      { teamId: 7, status: 'confirmed' },
      { teamId: 8, status: 'confirmed' },
      { teamId: 9, status: 'confirmed' },
      { teamId: 10, status: 'confirmed' },
      { teamId: 11, status: 'confirmed' },
      { teamId: 13, status: 'confirmed' },
      { teamId: 14, status: 'confirmed' },
    ],
    updatedAt: '2026-03-25T00:00:00Z',
  },
  {
    id: 3,
    slug: '3x3-exe-super-premier-singapore-2026-final',
    name: '3x3.EXE SUPER PREMIER 2025-26 FINAL（Singapore）',
    description: '3x3.EXE SUPER PREMIERシーズンファイナル（シンガポール）。',
    location: 'Sengkang Grand Mall（Singapore）',
    country: 'シンガポール',
    startDate: '2026-03-28',
    endDate: '2026-03-29',
    status: '開催予定',
    imageUrl: null,
    websiteUrl: 'https://3x3exe.com/superpremier/schedules/',
    xAccount: '3x3league',
    instagramAccount: '3x3.exe',
    tiktokAccount: null,
    participants: [],
    updatedAt: '2026-03-06T00:00:00Z',
  },
  {
    id: 4,
    slug: 'fiba-3x3-asia-cup-2026-singapore',
    name: 'FIBA 3x3 Asia Cup 2026',
    description: 'アジア各国代表が参加するFIBA公式3x3国際大会（アジアカップ）。',
    location: 'OCBC Square（1 Stadium Drive, Singapore 397629）',
    country: 'シンガポール',
    startDate: '2026-04-01',
    endDate: '2026-04-05',
    status: '開催予定',
    imageUrl: null,
    websiteUrl: 'https://fiba3x3.basketball/2026/asiacup',
    xAccount: 'FIBA3x3',
    instagramAccount: 'fiba3x3',
    tiktokAccount: null,
    participants: [],
    updatedAt: '2026-03-06T00:00:00Z',
  },
  {
    id: 5,
    slug: 'fiba-3x3-world-cup-qualifier-2026-singapore',
    name: 'FIBA 3x3 World Cup Qualifier 2026',
    description: 'FIBA 3x3 World Cup 2026の出場枠を争う代表戦（シンガポール開催）。',
    location: 'OCBC Square（The Kallang / 1 Stadium Drive, Singapore 397629）',
    country: 'シンガポール',
    startDate: '2026-04-11',
    endDate: '2026-04-12',
    status: '開催予定',
    imageUrl: null,
    websiteUrl: 'https://play.fiba3x3.com/events/54acbe47-9cae-48d9-adb6-f69fab7aaad5',
    xAccount: 'FIBA3x3',
    instagramAccount: 'fiba3x3',
    tiktokAccount: null,
    participants: [],
    updatedAt: '2026-03-06T00:00:00Z',
  },
  {
    id: 6,
    slug: 'fiba-3x3-world-tour-utsunomiya-opener-2026',
    name: 'FIBA 3x3 World Tour Utsunomiya Opener 2026',
    description: 'FIBA 3x3 World Tour 2026シーズン開幕戦（宇都宮）。',
    location: '宇都宮市（Utsunomiya, Tochigi, Japan）',
    country: '日本',
    startDate: '2026-04-25',
    endDate: '2026-04-26',
    status: '開催予定',
    imageUrl: null,
    websiteUrl: 'https://worldtour.fiba3x3.com/2026/utsunomiya',
    xAccount: 'FIBA3x3',
    instagramAccount: 'fiba3x3',
    tiktokAccount: null,
    participants: [],
    updatedAt: '2026-03-06T00:00:00Z',
  },
  {
    id: 7,
    slug: 'fiba-3x3-hengqin-challenger-2026',
    name: 'Hengqin Challenger 2026',
    description: 'FIBA 3x3 Challenger（ワールドツアー予選に直結する国際大会）横琴開催。',
    location: 'Hengqin（China）',
    country: '中国',
    startDate: '2026-04-11',
    endDate: '2026-04-12',
    status: '開催予定',
    imageUrl: null,
    websiteUrl: 'https://worldtour.fiba3x3.com/2026/challengers/hengqin',
    xAccount: 'FIBA3x3',
    instagramAccount: 'fiba3x3',
    tiktokAccount: null,
    participants: [],
    updatedAt: '2026-03-06T00:00:00Z',
  },
  {
    id: 8,
    slug: 'fiba-3x3-shibuya-city-challenger-2026',
    name: 'Shibuya City Challenger 2026',
    description: 'FIBA 3x3 Challenger（ワールドツアー予選に直結する国際大会）渋谷開催。',
    location: 'Shibuya, Tokyo（Japan）',
    country: '日本',
    startDate: '2026-04-18',
    endDate: '2026-04-19',
    status: '開催予定',
    imageUrl: null,
    websiteUrl: 'https://worldtour.fiba3x3.com/2026/challengers/shibuya',
    xAccount: 'FIBA3x3',
    instagramAccount: 'fiba3x3',
    tiktokAccount: null,
    participants: [],
    updatedAt: '2026-03-06T00:00:00Z',
  },
  {
    id: 9,
    slug: '3x3-exe-premier-japan-2026-women-round1-utsunomiya',
    name: '3x3.EXE PREMIER JAPAN 2026 WOMEN ROUND.1（宇都宮）',
    description: '女子リーグの開幕ラウンド（宇都宮開催）。',
    location: 'ライトキューブ宇都宮 大ホール（栃木県宇都宮市）',
    country: '日本',
    startDate: '2026-04-25',
    endDate: '2026-04-26',
    status: '開催予定',
    imageUrl: null,
    websiteUrl: 'https://3x3exe.com/premier/japan_2026_schedule/',
    xAccount: '3x3league',
    instagramAccount: '3x3.exe',
    tiktokAccount: null,
    participants: [],
    updatedAt: '2026-03-06T00:00:00Z',
  },
  {
    id: 10,
    slug: '3x3-exe-premier-japan-2026-men-round1-waterras',
    name: '3x3.EXE PREMIER JAPAN 2026 MEN ROUND.1（ワテラス）',
    description: '男子リーグの開幕ラウンド（ワテラス開催）。',
    location: 'ワテラス（東京都千代田区）',
    country: '日本',
    startDate: '2026-05-16',
    endDate: '2026-05-17',
    status: '開催予定',
    imageUrl: null,
    websiteUrl: 'https://3x3exe.com/premier/japan_2026_schedule/',
    xAccount: '3x3league',
    instagramAccount: '3x3.exe',
    tiktokAccount: null,
    participants: [],
    updatedAt: '2026-03-06T00:00:00Z',
  },
  {
    id: 11,
    slug: '3x3-exe-premier-japan-2026-men-round1-yaizu-port',
    name: '3x3.EXE PREMIER JAPAN 2026 MEN ROUND.1（焼津港）',
    description: '男子リーグROUND.1の別開催（焼津港）。',
    location: '焼津港（静岡県焼津市）',
    country: '日本',
    startDate: '2026-05-17',
    endDate: '2026-05-17',
    status: '開催予定',
    imageUrl: null,
    websiteUrl: 'https://3x3exe.com/premier/japan_2026_schedule/',
    xAccount: '3x3league',
    instagramAccount: '3x3.exe',
    tiktokAccount: null,
    participants: [],
    updatedAt: '2026-03-06T00:00:00Z',
  },
  {
    id: 12,
    slug: '3x3-exe-premier-japan-2026-women-round2-waterras',
    name: '3x3.EXE PREMIER JAPAN 2026 WOMEN ROUND.2（ワテラス）',
    description: '女子リーグROUND.2（ワテラス開催）。',
    location: 'ワテラス（東京都千代田区）',
    country: '日本',
    startDate: '2026-05-16',
    endDate: '2026-05-17',
    status: '開催予定',
    imageUrl: null,
    websiteUrl: 'https://3x3exe.com/premier/japan_2026_schedule/',
    xAccount: '3x3league',
    instagramAccount: '3x3.exe',
    tiktokAccount: null,
    participants: [],
    updatedAt: '2026-03-06T00:00:00Z',
  },
  {
    id: 13,
    slug: '3x3-exe-premier-japan-2026-men-round2-kashiwa-ario',
    name: '3x3.EXE PREMIER JAPAN 2026 MEN ROUND.2（セブンパーク アリオ柏）',
    description: '男子リーグROUND.2（柏開催）。※一部日程・会場は調整中表記あり。',
    location: 'セブンパーク アリオ柏 スマイル・パーク（千葉県柏市）',
    country: '日本',
    startDate: '2026-05-30',
    endDate: '2026-05-31',
    status: '開催予定',
    imageUrl: null,
    websiteUrl: 'https://3x3exe.com/premier/japan_2026_schedule/',
    xAccount: '3x3league',
    instagramAccount: '3x3.exe',
    tiktokAccount: null,
    participants: [],
    updatedAt: '2026-03-06T00:00:00Z',
  },
  {
    id: 14,
    slug: '3x3-exe-premier-japan-2026-women-round2-kashiwa-ario',
    name: '3x3.EXE PREMIER JAPAN 2026 WOMEN ROUND.2（セブンパーク アリオ柏）',
    description: '女子リーグROUND.2（柏開催）。',
    location: 'セブンパーク アリオ柏 スマイル・パーク（千葉県柏市）',
    country: '日本',
    startDate: '2026-05-30',
    endDate: '2026-05-30',
    status: '開催予定',
    imageUrl: null,
    websiteUrl: 'https://3x3exe.com/premier/japan_2026_schedule/',
    xAccount: '3x3league',
    instagramAccount: '3x3.exe',
    tiktokAccount: null,
    participants: [],
    updatedAt: '2026-03-25T00:00:00Z',
  },
  {
    id: 15,
    slug: '3x3-exe-premier-japan-2026-men-round2-kobe-univadome',
    name: '3x3.EXE PREMIER JAPAN 2026 MEN ROUND.2（キャンパススクェア / ユニバードーム）',
    description: '男子リーグROUND.2（神戸開催）。',
    location: 'キャンパススクェア（ユニバードーム）（兵庫県神戸市）',
    country: '日本',
    startDate: '2026-05-30',
    endDate: '2026-05-31',
    status: '開催予定',
    imageUrl: null,
    websiteUrl: 'https://3x3exe.com/premier/japan_2026_schedule/',
    xAccount: '3x3league',
    instagramAccount: '3x3.exe',
    tiktokAccount: null,
    participants: [],
    updatedAt: '2026-03-25T00:00:00Z',
  },
  {
    id: 16,
    slug: '3x3-exe-premier-japan-2026-women-round2-kobe-univadome',
    name: '3x3.EXE PREMIER JAPAN 2026 WOMEN ROUND.2（キャンパススクェア / ユニバードーム）',
    description: '女子リーグROUND.2（神戸開催）。',
    location: 'キャンパススクェア（ユニバードーム）（兵庫県神戸市）',
    country: '日本',
    startDate: '2026-05-30',
    endDate: '2026-05-30',
    status: '開催予定',
    imageUrl: null,
    websiteUrl: 'https://3x3exe.com/premier/japan_2026_schedule/',
    xAccount: '3x3league',
    instagramAccount: '3x3.exe',
    tiktokAccount: null,
    participants: [],
    updatedAt: '2026-03-25T00:00:00Z',
  },
  {
    id: 17,
    slug: '3x3-exe-premier-japan-2026-men-round3-ube',
    name: '3x3.EXE PREMIER JAPAN 2026 MEN ROUND.3 ALL CONFERENCE（恩田スポーツパーク）',
    description: '男子リーグROUND.3 ALL CONFERENCE（宇部開催）。',
    location: '恩田スポーツパーク（山口県宇部市）',
    country: '日本',
    startDate: '2026-06-13',
    endDate: '2026-06-14',
    status: '開催予定',
    imageUrl: null,
    websiteUrl: 'https://3x3exe.com/premier/japan_2026_schedule/',
    xAccount: '3x3league',
    instagramAccount: '3x3.exe',
    tiktokAccount: null,
    participants: [],
    updatedAt: '2026-03-25T00:00:00Z',
  },
  {
    id: 18,
    slug: '3x3-exe-premier-japan-2026-women-round3-ube',
    name: '3x3.EXE PREMIER JAPAN 2026 WOMEN ROUND.3（恩田スポーツパーク）',
    description: '女子リーグROUND.3（宇部開催）。',
    location: '恩田スポーツパーク（山口県宇部市）',
    country: '日本',
    startDate: '2026-06-13',
    endDate: '2026-06-14',
    status: '開催予定',
    imageUrl: null,
    websiteUrl: 'https://3x3exe.com/premier/japan_2026_schedule/',
    xAccount: '3x3league',
    instagramAccount: '3x3.exe',
    tiktokAccount: null,
    participants: [],
    updatedAt: '2026-03-25T00:00:00Z',
  },
  {
    id: 19,
    slug: '3x3-exe-premier-japan-2026-men-round4-nagoya',
    name: '3x3.EXE PREMIER JAPAN 2026 MEN ROUND.4（オアシス21）',
    description: '男子リーグROUND.4（名古屋開催）。',
    location: 'オアシス21 銀河の広場（愛知県名古屋市）',
    country: '日本',
    startDate: '2026-06-20',
    endDate: '2026-06-20',
    status: '開催予定',
    imageUrl: null,
    websiteUrl: 'https://3x3exe.com/premier/japan_2026_schedule/',
    xAccount: '3x3league',
    instagramAccount: '3x3.exe',
    tiktokAccount: null,
    participants: [],
    updatedAt: '2026-03-25T00:00:00Z',
  },
  {
    id: 20,
    slug: '3x3-exe-premier-japan-2026-men-round4-utsunomiya-arctown',
    name: '3x3.EXE PREMIER JAPAN 2026 MEN ROUND.4（アークタウン宇都宮）',
    description: '男子リーグROUND.4（宇都宮開催）。',
    location: 'アークタウン宇都宮（栃木県宇都宮市）',
    country: '日本',
    startDate: '2026-06-27',
    endDate: '2026-06-27',
    status: '開催予定',
    imageUrl: null,
    websiteUrl: 'https://3x3exe.com/premier/japan_2026_schedule/',
    xAccount: '3x3league',
    instagramAccount: '3x3.exe',
    tiktokAccount: null,
    participants: [],
    updatedAt: '2026-03-25T00:00:00Z',
  },
  {
    id: 21,
    slug: '3x3-exe-premier-japan-2026-women-round4-utsunomiya-arctown',
    name: '3x3.EXE PREMIER JAPAN 2026 WOMEN ROUND.4（アークタウン宇都宮）',
    description: '女子リーグROUND.4（宇都宮開催）。',
    location: 'アークタウン宇都宮（栃木県宇都宮市）',
    country: '日本',
    startDate: '2026-06-27',
    endDate: '2026-06-27',
    status: '開催予定',
    imageUrl: null,
    websiteUrl: 'https://3x3exe.com/premier/japan_2026_schedule/',
    xAccount: '3x3league',
    instagramAccount: '3x3.exe',
    tiktokAccount: null,
    participants: [],
    updatedAt: '2026-03-25T00:00:00Z',
  },
  {
    id: 22,
    slug: '3x3-exe-premier-japan-2026-playoffs-osaka',
    name: '3x3.EXE PREMIER JAPAN 2026 PLAYOFFS（グラングリーン大阪）',
    description: 'シーズンプレーオフ（男女合同・大阪開催）。',
    location: 'グラングリーン大阪 ロートハートスクエアうめきた（大阪府大阪市）',
    country: '日本',
    startDate: '2026-10-03',
    endDate: '2026-10-04',
    status: '開催予定',
    imageUrl: null,
    websiteUrl: 'https://3x3exe.com/premier/japan_2026_schedule/',
    xAccount: '3x3league',
    instagramAccount: '3x3.exe',
    tiktokAccount: null,
    participants: [],
    updatedAt: '2026-03-25T00:00:00Z',
  },
];

function applyFilters(events: PortalEvent[], filters: EventFilters): PortalEvent[] {
  let result = events;

  if (filters.search) {
    const q = filters.search.toLowerCase();
    result = result.filter(
      (e) =>
        e.name.toLowerCase().includes(q) ||
        e.location.toLowerCase().includes(q) ||
        e.country.toLowerCase().includes(q) ||
        (e.description ?? '').toLowerCase().includes(q)
    );
  }

  if (filters.status) {
    result = result.filter((e) => e.status === filters.status);
  }

  // 開催開始日の早い順に並べる
  result = [...result].sort((a, b) => a.startDate.localeCompare(b.startDate));

  return result;
}

export async function listEvents(filters: EventFilters): Promise<PaginatedResult<PortalEvent>> {
  const filtered = applyFilters(MOCK_EVENTS, filters);
  const total = filtered.length;
  const offset = (filters.page - 1) * filters.pageSize;
  const items = filtered.slice(offset, offset + filters.pageSize);

  return { items, total, page: filters.page, pageSize: filters.pageSize };
}

export async function getUpcomingEvents(limit = 5): Promise<PortalEvent[]> {
  const today = new Date().toISOString().slice(0, 10);
  return MOCK_EVENTS.filter((e) => e.startDate >= today)
    .sort((a, b) => a.startDate.localeCompare(b.startDate))
    .slice(0, limit);
}

export async function getEventById(id: number): Promise<PortalEvent | null> {
  return MOCK_EVENTS.find((e) => e.id === id) ?? null;
}
