/**
 * Team repository — mock implementation (no DB required).
 * Replace with DB-backed implementation when DATABASE_URL is available.
 */
import type { Team, TeamFilters, PaginatedResult } from '@/types/domain';

const MOCK_TEAMS: Team[] = [
  {
    id: 1,
    slug: 'shinagawa-city-3x3-1',
    name: 'SHINAGAWA CITY 3x3 BASKETBALL CLUB',
    location: '東京都',
    category: '一般クラブ',
    imageUrl: null,
    websiteUrl: 'https://www.shinagawa-city.com/3x3basketball/',
    xAccount: 'scbc_3x3',
    instagramAccount: 'shinagawacity3x3basketball',
    tiktokAccount: null,
    updatedAt: '2026-02-24T00:00:00Z',
  },
  {
    id: 2,
    slug: 'flowlish-gunma-2',
    name: 'FLOWLISH GUNMA',
    location: '群馬県',
    category: '一般クラブ',
    imageUrl: null,
    websiteUrl: 'https://flowlish-gunma.com/',
    xAccount: 'flowlish3x3',
    instagramAccount: 'flowlish3x3',
    tiktokAccount: null,
    updatedAt: '2026-02-24T00:00:00Z',
  },

  // ⭐追加
  {
    id: 3,
    slug: 'brisbane-3x3-exe-3',
    name: 'BRISBANE 3X3.EXE',
    location: 'Australia',
    category: 'EXE',
    imageUrl: null,
    websiteUrl: null,
    xAccount: null,
    instagramAccount: 'brisbane3x3exe',
    tiktokAccount: null,
    updatedAt: '2026-02-26T00:00:00Z',
  },
  {
    id: 4,
    slug: 'melbourne-magic-exe-4',
    name: 'MELBOURNE MAGIC.EXE',
    location: 'Australia',
    category: 'EXE',
    imageUrl: null,
    websiteUrl: null,
    xAccount: null,
    instagramAccount: 'melbournemagic3x3',
    tiktokAccount: null,
    updatedAt: '2026-02-26T00:00:00Z',
  },
  {
    id: 5,
    slug: 'zethree-ishikawa-exe-5',
    name: 'ZETHREE ISHIKAWA.EXE',
    location: '石川県',
    category: 'EXE',
    imageUrl: null,
    websiteUrl: null,
    xAccount: null,
    instagramAccount: 'zethree3x3',
    tiktokAccount: null,
    updatedAt: '2026-02-26T00:00:00Z',
  },
  {
    id: 6,
    slug: 'utsunomiya-brex-exe-6',
    name: 'UTSUNOMIYA BREX.EXE',
    location: '栃木県',
    category: 'EXE',
    imageUrl: null,
    websiteUrl: 'https://www.utsunomiyabrex.com/',
    xAccount: 'brex3x3',
    instagramAccount: null,
    tiktokAccount: null,
    updatedAt: '2026-02-26T00:00:00Z',
  },
  {
    id: 7,
    slug: 'hachinohe-dime-exe-7',
    name: 'HACHINOHE DIME.EXE',
    location: '青森県',
    category: 'EXE',
    imageUrl: null,
    websiteUrl: 'https://www.dime-3x3.com/',
    xAccount: 'hachinohe_dime',
    instagramAccount: 'hachinohe_dime',
    tiktokAccount: null,
    updatedAt: '2026-02-26T00:00:00Z',
  },
  {
    id: 8,
    slug: 'minakami-town-exe-8',
    name: 'MINAKAMI TOWN.EXE',
    location: '群馬県',
    category: 'EXE',
    imageUrl: null,
    websiteUrl: null,
    xAccount: null,
    instagramAccount: 'minakami3x3',
    tiktokAccount: null,
    updatedAt: '2026-02-26T00:00:00Z',
  },
  {
    id: 9,
    slug: 'rn-sport-exe-9',
    name: 'RN SPORT.EXE',
    location: 'Japan',
    category: 'EXE',
    imageUrl: null,
    websiteUrl: null,
    xAccount: null,
    instagramAccount: null,
    tiktokAccount: null,
    updatedAt: '2026-02-26T00:00:00Z',
  },
  {
    id: 10,
    slug: 'shonan-seaside-exe-10',
    name: 'SHONAN SEASIDE.EXE',
    location: '神奈川県',
    category: 'EXE',
    imageUrl: null,
    websiteUrl: null,
    xAccount: null,
    instagramAccount: 'shonanseaside3x3',
    tiktokAccount: null,
    updatedAt: '2026-02-26T00:00:00Z',
  },
  {
    id: 11,
    slug: 'singapore-exe-11',
    name: 'SINGAPORE',
    location: 'Singapore',
    category: '代表',
    imageUrl: null,
    websiteUrl: null,
    xAccount: 'sgbasketball',
    instagramAccount: 'sgbasketball',
    tiktokAccount: null,
    updatedAt: '2026-02-26T00:00:00Z',
  },
  {
    id: 12,
    slug: 'singapore-u23-exe-12',
    name: 'SINGAPORE U-23',
    location: 'Singapore',
    category: 'U23',
    imageUrl: null,
    websiteUrl: null,
    xAccount: null,
    instagramAccount: null,
    tiktokAccount: null,
    updatedAt: '2026-02-26T00:00:00Z',
  },
  {
    id: 13,
    slug: 'lugano-exe-13',
    name: 'LUGANO',
    location: 'Switzerland',
    category: '招待',
    imageUrl: null,
    websiteUrl: null,
    xAccount: '3x3lugano',
    instagramAccount: '3x3lugano',
    tiktokAccount: null,
    updatedAt: '2026-02-26T00:00:00Z',
  },
  {
    id: 14,
    slug: 'ct-monkey-exe-14',
    name: 'CT MONKEY.EXE',
    location: 'Thailand',
    category: 'EXE',
    imageUrl: null,
    websiteUrl: null,
    xAccount: null,
    instagramAccount: null,
    tiktokAccount: null,
    updatedAt: '2026-03-25T00:00:00Z',
  },

  // World Tour teams
  {
    id: 15,
    slug: 'ub-srb-15',
    name: 'Ub',
    location: 'Serbia',
    category: 'WT',
    imageUrl: null,
    websiteUrl: null,
    xAccount: null,
    instagramAccount: '3x3ub',
    tiktokAccount: null,
    updatedAt: '2026-03-26T00:00:00Z',
  },
  {
    id: 16,
    slug: 'liman-srb-16',
    name: 'Liman',
    location: 'Serbia',
    category: 'WT',
    imageUrl: null,
    websiteUrl: null,
    xAccount: 'liman3x3',
    instagramAccount: 'liman3x3',
    tiktokAccount: null,
    updatedAt: '2026-03-26T00:00:00Z',
  },
  {
    id: 17,
    slug: 'miami-usa-17',
    name: 'Miami',
    location: 'USA',
    category: 'WT',
    imageUrl: null,
    websiteUrl: 'https://www.usab.com/teams/3x3-mens-world-tour',
    xAccount: 'usab3x3',
    instagramAccount: 'teammiami3x3',
    tiktokAccount: null,
    updatedAt: '2026-03-26T00:00:00Z',
  },
  {
    id: 18,
    slug: 'amsterdam-ned-18',
    name: 'Amsterdam HiPRO',
    location: 'Netherlands',
    category: 'WT',
    imageUrl: null,
    websiteUrl: null,
    xAccount: null,
    instagramAccount: 'teamamsterdam3x3_hipro',
    tiktokAccount: null,
    updatedAt: '2026-03-26T00:00:00Z',
  },
  {
    id: 19,
    slug: 'raudondvaris-ltu-19',
    name: 'Raudondvaris',
    location: 'Lithuania',
    category: 'WT',
    imageUrl: null,
    websiteUrl: null,
    xAccount: null,
    instagramAccount: 'raudondvaris_hoptrans_3x3',
    tiktokAccount: null,
    updatedAt: '2026-03-26T00:00:00Z',
  },
  {
    id: 20,
    slug: 'shanghai-chn-20',
    name: 'Shanghai',
    location: 'China',
    category: 'WT',
    imageUrl: null,
    websiteUrl: null,
    xAccount: null,
    instagramAccount: null,
    tiktokAccount: null,
    updatedAt: '2026-03-26T00:00:00Z',
  },
  {
    id: 21,
    slug: 'skyliners-ger-21',
    name: 'Skyliners',
    location: 'Germany',
    category: 'WT',
    imageUrl: null,
    websiteUrl: null,
    xAccount: null,
    instagramAccount: 'skylinersev',
    tiktokAccount: null,
    updatedAt: '2026-03-26T00:00:00Z',
  },
  {
    id: 22,
    slug: 'toulouse-fra-22',
    name: 'Toulouse',
    location: 'France',
    category: 'WT',
    imageUrl: null,
    websiteUrl: 'https://toulouse3x3.fr/',
    xAccount: 'toulouse3x3',
    instagramAccount: 'toulouse3x3',
    tiktokAccount: null,
    updatedAt: '2026-03-26T00:00:00Z',
  },
  {
    id: 23,
    slug: 'vienna-aut-23',
    name: 'Vienna',
    location: 'Austria',
    category: 'WT',
    imageUrl: null,
    websiteUrl: null,
    xAccount: null,
    instagramAccount: '3x3vienna',
    tiktokAccount: null,
    updatedAt: '2026-03-26T00:00:00Z',
  },
  {
    id: 24,
    slug: 'antwerp-bel-24',
    name: 'Antwerp',
    location: 'Belgium',
    category: 'WT',
    imageUrl: null,
    websiteUrl: 'https://www.3x3teamantwerp.be/',
    xAccount: null,
    instagramAccount: '3x3teamantwerp',
    tiktokAccount: null,
    updatedAt: '2026-03-26T00:00:00Z',
  },

  // PREMIER WOMEN teams
  {
    id: 25,
    slug: 'st-kasumi-exe-25',
    name: 'ST-KASUMI.EXE',
    location: '茨城県',
    category: 'EXE',
    imageUrl: null,
    websiteUrl: null,
    xAccount: null,
    instagramAccount: null,
    tiktokAccount: null,
    updatedAt: '2026-03-26T00:00:00Z',
  },
  {
    id: 26,
    slug: 'tokyo-verdy-exe-26',
    name: 'TOKYO VERDY.EXE',
    location: '東京都',
    category: 'EXE',
    imageUrl: null,
    websiteUrl: null,
    xAccount: null,
    instagramAccount: null,
    tiktokAccount: null,
    updatedAt: '2026-03-26T00:00:00Z',
  },
  {
    id: 27,
    slug: 'shinjuku-givers-exe-27',
    name: 'SHINJUKU GIVERS.EXE',
    location: '東京都',
    category: 'EXE',
    imageUrl: null,
    websiteUrl: null,
    xAccount: null,
    instagramAccount: null,
    tiktokAccount: null,
    updatedAt: '2026-03-26T00:00:00Z',
  },
  {
    id: 28,
    slug: 'taito-owls-exe-28',
    name: 'TAITO OWLS.EXE',
    location: '東京都',
    category: 'EXE',
    imageUrl: null,
    websiteUrl: null,
    xAccount: null,
    instagramAccount: null,
    tiktokAccount: null,
    updatedAt: '2026-03-26T00:00:00Z',
  },
  {
    id: 29,
    slug: 'sanjo-beaters-exe-29',
    name: 'SANJO BEATERS.EXE',
    location: '新潟県',
    category: 'EXE',
    imageUrl: null,
    websiteUrl: null,
    xAccount: null,
    instagramAccount: null,
    tiktokAccount: null,
    updatedAt: '2026-03-26T00:00:00Z',
  },
  {
    id: 30,
    slug: 'echake-na-noto-exe-30',
    name: 'ECHAKE-NA NOTO.EXE',
    location: '石川県',
    category: 'EXE',
    imageUrl: null,
    websiteUrl: null,
    xAccount: null,
    instagramAccount: null,
    tiktokAccount: null,
    updatedAt: '2026-03-26T00:00:00Z',
  },
  {
    id: 31,
    slug: 'uenohara-sunrise-exe-31',
    name: 'UENOHARA SUNRISE.EXE',
    location: '山梨県',
    category: 'EXE',
    imageUrl: null,
    websiteUrl: null,
    xAccount: null,
    instagramAccount: null,
    tiktokAccount: null,
    updatedAt: '2026-03-26T00:00:00Z',
  },
  {
    id: 32,
    slug: 'shinshu-saku-region-exe-32',
    name: 'SHINSHU SAKU REGION.EXE',
    location: '長野県',
    category: 'EXE',
    imageUrl: null,
    websiteUrl: null,
    xAccount: 'region3x3',
    instagramAccount: 'region3x3',
    tiktokAccount: null,
    updatedAt: '2026-03-26T00:00:00Z',
  },
  {
    id: 33,
    slug: 'gifu-valkyries-exe-33',
    name: 'GIFU VALKYRIES.EXE',
    location: '岐阜県',
    category: 'EXE',
    imageUrl: null,
    websiteUrl: null,
    xAccount: null,
    instagramAccount: null,
    tiktokAccount: null,
    updatedAt: '2026-03-26T00:00:00Z',
  },
  {
    id: 34,
    slug: 'nagoya-derraze-exe-34',
    name: 'NAGOYA DERRAZE.EXE',
    location: '愛知県',
    category: 'EXE',
    imageUrl: null,
    websiteUrl: null,
    xAccount: null,
    instagramAccount: null,
    tiktokAccount: null,
    updatedAt: '2026-03-26T00:00:00Z',
  },
  {
    id: 35,
    slug: 'athlete-x-kansai-exe-35',
    name: 'ATHLETE X KANSAI.EXE',
    location: '京都府',
    category: 'EXE',
    imageUrl: null,
    websiteUrl: null,
    xAccount: null,
    instagramAccount: null,
    tiktokAccount: null,
    updatedAt: '2026-03-26T00:00:00Z',
  },
];

export async function listTeams(filters: TeamFilters): Promise<PaginatedResult<Team>> {
  let result = MOCK_TEAMS;

  if (filters.search) {
    const q = filters.search.toLowerCase();
    result = result.filter(
      (t) => t.name.toLowerCase().includes(q) || t.location.toLowerCase().includes(q)
    );
  }

  if (filters.category) {
    result = result.filter((t) => t.category === filters.category);
  }

  const total = result.length;
  const offset = (filters.page - 1) * filters.pageSize;
  const items = result.slice(offset, offset + filters.pageSize);

  return { items, total, page: filters.page, pageSize: filters.pageSize };
}

export async function getTeamById(id: number): Promise<Team | null> {
  return MOCK_TEAMS.find((t) => t.id === id) ?? null;
}

export async function getAllTeams(): Promise<Team[]> {
  return [...MOCK_TEAMS].sort((a, b) => a.name.localeCompare(b.name));
}

export async function getTeamsByIds(ids: number[]): Promise<Team[]> {
  if (ids.length === 0) return [];
  // 元の ids の順序を保持して返す
  return ids
    .map((id) => MOCK_TEAMS.find((t) => t.id === id))
    .filter((t): t is Team => t !== undefined);
}
